model {
  file: "model.sdf"
}
name: "boxes"
description: "boxes"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Schleich"
}
annotations {
  key: "gtin"
  value: "4005086160927"
}
annotations {
  key: "sku"
  value: "16092"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
