<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--
  Author: Kelsey Hawkins
  Contributers: Jimmy Da Silva, Ajit Krisshna N L, Muhammad Asif Rana
-->

  <xacro:arg name="joint_limited" default="false" />

  <!--<xacro:include filename="$(find nist_gear)/robots/ur10/ur_description/urdf/common.gazebo.xacro" />-->
  <xacro:include filename="$(find nist_gear)/robots/ur10/ur_description/urdf/ur.transmission.xacro" />
  <xacro:include filename="$(find nist_gear)/robots/ur10/ur_description/urdf/ur.gazebo.xacro" />

  <!-- Inertia parameters -->
  <xacro:property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
  <xacro:property name="shoulder_mass" value="7.778" />
  <xacro:property name="upper_arm_mass" value="12.93" />
  <xacro:property name="forearm_mass" value="3.87" />
  <xacro:property name="wrist_1_mass" value="1.96" />
  <xacro:property name="wrist_2_mass" value="1.96" />
  <xacro:property name="wrist_3_mass" value="0.202" />

  <!-- These parameters are borrowed from the urcontrol.conf file
       but are not verified for the correct permutation.
       The permutation was guessed by looking at the UR5 parameters.
       Serious use of these parameters needs further inspection. -->
  <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
  <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
  <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
  <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
  <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
  <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <xacro:property name="ur10_d1" value="0.1273" />
  <xacro:property name="ur10_a2" value="-0.612" />
  <xacro:property name="ur10_a3" value="-0.5723" />
  <xacro:property name="ur10_d4" value="0.163941" />
  <xacro:property name="ur10_d5" value="0.1157" />
  <xacro:property name="ur10_d6" value="0.0922" />

  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <xacro:property name="shoulder_offset" value="0.220941" />  <!-- measured from model -->
  <xacro:property name="elbow_offset" value="-0.1719" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <xacro:property name="shoulder_height" value="${ur10_d1}" />
  <xacro:property name="upper_arm_length" value="${-ur10_a2}" />
  <xacro:property name="forearm_length" value="${-ur10_a3}" />
  <xacro:property name="wrist_1_length" value="${ur10_d4 - elbow_offset - shoulder_offset}" />
  <xacro:property name="wrist_2_length" value="${ur10_d5}" />
  <xacro:property name="wrist_3_length" value="${ur10_d6}" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="ur10_robot" params="parent prefix *origin">
    <link name="${prefix}base_link" >
      <visual>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/visual/base.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/collision/base.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
        <origin xyz="0.09996 -0.0275 2.32214" rpy="0 0 1.57" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="${prefix}base_link">
      <selfCollide>1</selfCollide>
    </gazebo>

    <!-- Joints -->
    <joint name="${prefix}arm_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}base_link"/>
    </joint>

    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy=" 0.0 0.0 0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="$(arg joint_limited)">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="${330.0 + 200}" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="$(arg joint_limited)">
        <limit lower="${-pi}" upper="${pi}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="20.0" friction="20.0"/>
    </joint>

    <gazebo reference="${prefix}shoulder_pan_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

    <link name="${prefix}shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/visual/shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="${prefix}shoulder_link">
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link = "${prefix}upper_arm_link" />
      <!--zeid-->
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0" />
      <!-- <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 0 0.0" /> -->
      <axis xyz="0 1 0" />
      <xacro:unless value="$(arg joint_limited)">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="$(arg joint_limited)">
        <limit lower="${-pi}" upper="${pi}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="20.0" friction="0.0"/>
    </joint>

    <gazebo reference="${prefix}shoulder_lift_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

    <link name="${prefix}upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/visual/upperarm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/collision/upperarm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="${prefix}upper_arm_link">
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link = "${prefix}forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="$(arg joint_limited)">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
      </xacro:unless>
      <xacro:if value="$(arg joint_limited)">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
      </xacro:if>
      <dynamics damping="20.0" friction="0.0"/>
    </joint>

    <gazebo reference="${prefix}elbow_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

    <link name="${prefix}forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/visual/forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/collision/forearm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="${prefix}forearm_link">
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link = "${prefix}wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="$(arg joint_limited)">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="$(arg joint_limited)">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="1.0" friction="0.0"/>
    </joint>

    <gazebo reference="${prefix}wrist_1_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

    <link name="${prefix}wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/visual/wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/collision/wrist1.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="${prefix}wrist1_link">
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link = "${prefix}wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="$(arg joint_limited)">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="$(arg joint_limited)">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="1.0" friction="0.0"/>
    </joint>

    <gazebo reference="${prefix}wrist_2_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

    <link name="${prefix}wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/visual/wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/collision/wrist2.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="${prefix}wrist2_link">
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="$(arg joint_limited)">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="$(arg joint_limited)">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.5" friction="0.0"/>
    </joint>

    <gazebo reference="${prefix}wrist_3_joint">
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

    <link name="${prefix}wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/visual/wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://nist_gear/robots/ur10/ur_description/meshes/ur10/collision/wrist3.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <gazebo reference="${prefix}wrist3_link">
      <selfCollide>1</selfCollide>
    </gazebo>

    <joint name="${prefix}ee_fixed_joint" type="fixed">
      <parent link="${prefix}wrist_3_link" />
      <child link = "${prefix}ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${prefix}ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>

    <!-- setup transmissions
    <xacro:ur_arm_transmission prefix="${prefix}" />
  -->
    <!-- instantiate the arm -->
    <xacro:ur_arm_gazebo prefix="${prefix}" />

    <!-- ROS base_link to UR 'Base' Coordinates transform -->
    <link name="${prefix}base"/>
    <joint name="${prefix}base_link-base_fixed_joint" type="fixed">
      <!-- NOTE: this rotation is only needed as long as base_link itself is
                 not corrected wrt the real robot (ie: rotated over 180
                 degrees)
      -->
      <origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="${prefix}tool0"/>
    <joint name="${prefix}wrist_3_link-tool0_fixed_joint" type="fixed">
      <origin xyz="0 ${wrist_3_length} 0" rpy="${pi/-2.0} 0 0"/>
      <parent link="${prefix}wrist_3_link"/>
      <child link="${prefix}tool0"/>
    </joint>
  </xacro:macro>
</robot>
