PENALTIES:
  GOOD_CELL_IN_INSPECTION_BIN: 50
  CELL_IN_CONVEYOR_BIN: 25
  OBJECT_ON_INVALID_SURFACE: 25
  AGV_COLLISION: 100
  ROBOT_COLLISION: 100

WEIGHTS:
  W1: 5000
  W2: 12000
  W3: 1000
  W4: 500
  W5: 600
  W6: 1000
  W7: 500

SENSOR_BUDGET: 9600
NOMINAL_INSPECTION_TIME: 4
NOMINAL_HIGH_PRIORITY_EXECUTION_DURATION: 150
