PENALTIES:
  GOOD_CELL_IN_INSPECTION_BIN: 100
  CELL_IN_CONVEYOR_BIN: 50 
  OBJECT_ON_INVALID_SURFACE: 50
  AGV_COLLISION: 300
  ROBOT_COLLISION: 50

WEIGHTS:
  W1: 500
  W2: 800
  W3: 175
  W4: 125
  W5: 150
  W6: 500
  W7: 100

SENSOR_BUDGET: 7000
NOMINAL_INSPECTION_TIME: 4
NOMINAL_HIGH_PRIORITY_EXECUTION_DURATION: 130