# Trial Name: kitting.yaml
# ARIAC2024

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [3, 8] 
  slots: [1, 4]

assembly_inserts:
  as1: '0.0'
  as2: '0.0'
  as3: '0.0'
  as4: '0.0'

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'pump'
        color: 'purple'
        slots: [1, 3, 7, 9]
    bin6:
      - type: 'battery'
        color: 'blue'
        slots: [1, 3, 7, 9]

orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 3
        - type: 'pump'
          color: 'purple'
          quadrant: 1