<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ariac_app</name>
  <version>2025.2.0</version>
  <description>TODO: Package description</description>
  <maintainer email="justin.albrecht@nist.gov">Justin Albrecht</maintainer>
  <license>BSD-3-Clause</license>

  <depend>ariac_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
