<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ariac_db</name>
  <version>2025.3.4</version>
  <description>Package containing scripts and nodes for creating and working with the ariac database</description>
  <maintainer email="justin.albrecht@nist.gov">Justin Albrecht</maintainer>
  <license>BSD-3-Clause</license>

  <export>
    <build_type>ament_python</build_type>
  </export>

  <depend>sqlite3</depend>

</package>
