gantry_x_axis_joint: 2
gantry_y_axis_joint: 0
gantry_rotation_joint: -1.571
shoulder_pan_joint: 0.0
shoulder_lift_joint: -1.57
elbow_joint: 1.57
wrist_1_joint: 3.14
wrist_2_joint: -1.571
wrist_3_joint: 0.0