gantry_welder:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      
  joint_trajectory_controller:
    ros__parameters:
      joints:
        - longitudinal_slide_joint
        - transverse_slide_joint
        - vertical_lift_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 1000.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false