inspection_robot_2:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      gripper_controller:
        type: robotiq_gripper_controller/RobotiqGripperController
  
  joint_trajectory_controller:
    ros__parameters:
      joints:
        - inspection_robot_2_shoulder_pan_joint
        - inspection_robot_2_shoulder_lift_joint
        - inspection_robot_2_elbow_joint
        - inspection_robot_2_wrist_1_joint
        - inspection_robot_2_wrist_2_joint
        - inspection_robot_2_wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 1000.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
  
  gripper_controller:
    ros__parameters:
      joint: inspection_robot_2_robotiq_85_left_knuckle_joint