# Submit a kitting shipment for scoring
# The AGV will move to assembly_station_name
# Scoring will be applied on shipment_type


# Name of the assembly station
string assembly_station_name
#shipment type (e.g., 'order_0_kitting_shipment_0')
string shipment_type

---
bool success
string message
