<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotiq_gripper_controller</name>
  <version>2025.3.2</version>
  <description>TODO: Package description</description>
  <maintainer email="justin.albrecht@nist.gov">Justin Albrecht</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>controller_interface</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>control_toolbox</depend>
  <depend>generate_parameter_library</depend>
  <depend>ariac_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
