<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="base_len" value="0.2" />
<xacro:property name="actuator_len" value="10" />
<xacro:property name="actuator_height" value="0.1" />

<xacro:arg name="use_velocity_interface" default="false" />
<xacro:arg name="use_effort_interface" default="false" />

<xacro:macro name="create_linear_arm_actuator" params="base_link">

  <link name="linear_arm_actuator">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.1" ixy="0" ixz="0"
               iyy="0.1" iyz="0"
               izz="0.1" />
      <mass value="1" />
    </inertial>
  </link>

  <gazebo reference="linear_arm_actuator">
    <material>Gazebo/GreyTransparent</material>
  </gazebo>

  <joint name="linear_arm_actuator_joint" type="prismatic">
    <parent link="linear_arm_actuator" />
    <child link="${base_link}" />

    <axis xyz="0 1 0" />
    <limit lower="${-1 * ((actuator_len / 2) - base_len)}"
           upper="${(actuator_len / 2) - base_len}"
           effort="1000"
           velocity="1" />
    <origin xyz="0 0 ${base_len / 2}" rpy="0 0 0" />
    <dynamics damping="20.0" friction="500.0" />
  </joint>

  <gazebo reference="linear_arm_actuator_joint">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>

  <xacro:linear_arm_actuator_transmission />

</xacro:macro>

<xacro:macro name="linear_arm_actuator_transmission">

  <!-- if use_position_interface create PositionJointInterface based transmissions -->
  <xacro:unless value="$(arg use_velocity_interface)">
  <xacro:unless value="$(arg use_effort_interface)">
    <xacro:linear_arm_actuator_transmission_impl joint_interface="hardware_interface/PositionJointInterface" />
  </xacro:unless>
  </xacro:unless>
  <!-- if use_velocity_interface create VelocityJointInterface based transmissions -->
  <xacro:if value="$(arg use_velocity_interface)">
    <xacro:linear_arm_actuator_transmission_impl joint_interface="hardware_interface/VelocityJointInterface" />
  </xacro:if>
  <!-- if use_effort_interface create EffortJointInterface based transmissions -->
  <xacro:if value="$(arg use_effort_interface)">
    <xacro:linear_arm_actuator_transmission_impl joint_interface="hardware_interface/EffortJointInterface" />
  </xacro:if>

</xacro:macro>

<xacro:macro name="linear_arm_actuator_transmission_impl" params="joint_interface">

  <transmission name="linear_arm_actuator_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="linear_arm_actuator_joint">
      <hardwareInterface>${joint_interface}</hardwareInterface>
    </joint>
    <actuator name="linear_arm_actuator_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</xacro:macro>

</robot>
