name: CI

on: [push, pull_request, pull_request_review]

jobs:
  build_test:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, UPSTREAM_WORKSPACE: 2021.repos}
          - {ROS_DISTRO: melodic, UPSTREAM_WORKSPACE: 2020.repos}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
